name: Run Tests
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
permissions:
  contents: read
jobs:
  test:
    strategy:
      max-parallel: 2
      matrix:
        os: [macos, ubuntu]
        go: ["1.18"]
        include:
          - os: macos
            gopath: /Users/runner/go
            gocache: /Users/runner/Library/Caches/go-build
          - os: ubuntu
            gopath: /home/runner/go
            gocache: /home/runner/.cache/go-build
    name: ${{ matrix.os }} @ Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}-latest
    env:
      GO111MODULE: off
      GOPATH: ${{ matrix.gopath }}:${{ github.workspace }}
      CGO_ENABLED: 1
      WORKDIR: src/github.com/eudore/eudore/
      PACKAGES: github.com/eudore/eudore,github.com/eudore/eudore/middleware
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ env.WORKDIR }}
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-go-${{ hashFiles('src/github.com/eudore/eudore/go.mod') }}
          restore-keys: ${{ runner.os }}-go-
          path: |
            ${{ matrix.gopath }}
            ${{ matrix.gocache }}
      - name: Run Debug
        run: rm -f _example/logger_test.go
      - name: Run Go Get 
        run: for pkg in $(go list -json _example/*_test.go | jq -r '.XTestImports[]' | grep -E "github|monkey" | grep -v eudore); do go get -v $pkg; done
      - name: Run Tests
        run: go test -v -timeout=1m -race -cover -coverprofile=coverage.out -coverpkg='${{ env.PACKAGES }}' _example/*_test.go | tee output
      - name: Run Notice
        if: ${{ strategy.job-index == 0 }}
        run: 'echo "::notice::$(tail -3 output | grep "coverage: ")"'
      - name: Run Coverage
        if: ${{ strategy.job-index == 0 }}
        run: go tool cover -html coverage.out -o coverage.html
      - uses: actions/upload-artifact@v3
        if: ${{ strategy.job-index == 0 }}
        with:
          name: Coverage-eudore-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.go }}
          path: ${{ env.WORKDIR }}/coverage.html
        
