name: Run Tests
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: read
jobs:
  test:
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: ['1.18', '1.19', '1.20']
        include:
          - os: ubuntu-latest
            go-build: ~/.cache/go-build
          - os: macos-latest
            go-build: ~/Library/Caches/go-build
    name: ${{ matrix.os }} @ Go ${{ matrix.go }} ${{ matrix.test-tags }}
    runs-on: ${{ matrix.os }}
    env:
      GOPATH: /home/runner/go:/home/runner/work/action-demo/action-demo
      GO111MODULE: off
      CGO_ENABLED: 1
    steps:
      - uses: actions/checkout@v3
        with:
          path: src/github.com/eudore/eudore
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/cache@v3
        with:
          path: |
            ${{ matrix.go-build }}
            ~/go
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run goget 
        working-directory: src/github.com/eudore/eudore/_example/
        run: |
          go get -v bou.ke/monkey
          for pkg in $(go list -json *_test.go | jq -r '.XTestImports[]' | grep github | grep -v eudore); do echo $pkg; done
          mkdir logger
      - name: Run Tests1
        working-directory: src/github.com/eudore/eudore/_example/
        run: sudo pwd
      - name: Run Tests
        working-directory: src/github.com/eudore/eudore/_example/
        run: go test -i -v -run=App -timeout=2m -race -cover -coverprofile=coverage.out -coverpkg='github.com/eudore/eudore,github.com/eudore/eudore/middleware' *_test.go
